package mainPackage;

/**
 * Package: PACKAGE_NAME
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 28.01.2018 2018
 */
public class Methode {
    String monat = "1";
    int count = 10;

    public void printMonat(String monat) {

        switch (monat)

        {
            case "1":
            case "01":
                System.out.println(" thang 1");
                break;

            default:
                System.out.println("no month ");


        }
    }

    public void Schleife(int x) {
        if (x == 5) {
            while (x >= 0) {
                System.out.println(x + " While");
                x--;
            }
        } else if (x == 10) {
            do {
                System.out.println(x + " do");
                x--;
            } while (x > 0);
        } else if (x == 15) {
            for (int i = 0; i < x; i++) {
                System.out.println(i + " for");
            }

        } else if (x == 20) {
            int[] array = new int[x];
            for (int i = 0; i < array.length; i++) {
                array[i] = i+1;
                System.out.println(array[i] + " for Array");

            }
            for(int y : array){
                System.out.println(y + " in Array");
            }

        }
    }

}
