package mainPackage;

/**
 * Package: PACKAGE_NAME
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 23.01.2018 2018
 */
public class Variable {

    int zahlt; // ca 2 miliarde
    long großeZahl; // sehr groß
    short kleineZahl; //sehr kleine Zahl
    byte sehrkleinezahl; // sehkleineZahl
    double geneuerKommaZahl; // sehr genauer Kommazahl
    char zeichen;
    boolean wahrFalsch;
    String text; // Zeichenreihe

    public Variable() {
        System.out.println("");
    }


}
