package klassen.Automat;

/**
 * Package: klassen.Automat
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 20.02.2018 2018
 */
public class Automat {
    int zustand;
    int input;
    int outut;

    public Automat() {
        zustand = 0; // Starten bei 0
    }

    public void lauf(int _input) {
        switch (zustand) {
            case 0:
                if (_input == 0) {
                    outut = 1;
                    System.out.println("aktueller Zustand: " + zustand + " + Input: " + _input + " -> Output: " + outut);
                    zustand = 0;
                    break;
                } else if (_input == 1) {
                    outut = 0;
                    System.out.println("aktueller Zustand: " + zustand + " + Input: " + _input + " -> Output: " + outut);
                    zustand = 1;
                    break;
                } else {
                    System.out.println("fehlerhafter Input: " + _input);
                    break;
                }
            case 1:
                if (_input == 0) {
                    outut = 0;
                    System.out.println("aktueller Zustand: " + zustand + " + Input: " + _input + " -> Output: " + outut);
                    zustand = 1;
                    break;
                } else if (_input == 1) {
                    outut = 1;
                    System.out.println("aktueller Zustand: " + zustand + " + Input: " + _input + " -> Output: " + outut);
                    zustand = 2;
                    break;
                } else {
                    System.out.println("fehlerhafter Input: " + _input);
                }
            case 2:
                if (_input == 0) {
                    outut = 1;
                    System.out.println("aktueller Zustand: " + zustand + " + Input: " + _input + " -> Output: " + outut);
                    zustand = 0;
                    break;
                } else if (_input == 1) {
                    outut = 1;
                    System.out.println("aktueller Zustand: " + zustand + " + Input: " + _input + " -> Output: " + outut);
                    zustand = 2;
                    break;
                } else {
                    System.out.println("fehlerhafter Input: " + _input);
                    break;
                }

            default:
                System.out.println("fehlerhafter Zustand: " + zustand);
        }
    }

    public void sendInput(String in) {
        if (!in.equals(" ")) {
            System.out.println(getClass().getName());
            for (int i = 0; i < in.length(); i++) {
                try {
                    int input = Character.getNumericValue(in.charAt(i));
                    lauf(input);

                } catch (Exception e) {
                    e.printStackTrace();
                }

            }

        } else System.out.println("leeres String wurde als Input verwendet!");

    }

}
