package klassen.Tree;

/**
 * Package: klassen.Tree
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 06.03.2018 2018
 */
public class Node {
    Node links = null;
    Node rechts = null;
    Node parent = null;
    int wert;
    public Node(int wert, Node parent){
        this.wert = wert;
        this.parent = parent;
    }
}
