package klassen.enums;

import java.text.DecimalFormat;

/**
 * Package: klassen.enums
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 19.02.2018 2018
 */
public class Enum {

    public enum Alkohol {
        WEIN(12), BIER(5.2), BANNANE(1), WASSER(0);
        private final double alkoProzent;

        Alkohol(double alkoProzent) {
            this.alkoProzent = alkoProzent;
        }

        public double alkoGehalt() {
            return alkoProzent;
        }

        public String abbauZeit(double menge, double gewicht) {
            double mengeAlko = menge * alkoGehalt() / 100;
            double abbauZeiten = 9090.9 * mengeAlko / gewicht;
            return "Abbaudauer " + (new DecimalFormat("0.0").format(abbauZeiten) + "h bei " + menge + " liter " + toString() + " bei  Gewicht von: " + gewicht);

        }
    }

    public void enumTest0(Alkohol alko, double menge, double gewicht) {
        System.out.println("Alkoholgehalt von " + alko + " ist: " + alko.alkoGehalt());
        System.out.println(alko.abbauZeit(menge, gewicht));

    }

    enum Figur {
        RECHECK("RE") {
            public double flaeche(double a, double b) {
                return a * b;
            }
        },
        DREIECK("DR") {
            public double flaeche(double a, double b) {
                return a * b / 2;
            }
        },
        ELLIPSE("EL") {
            public double flaeche(double a, double b) {
                return a * b * Math.PI / 4;
            }
        },;

        private final String kuerzel;

        public String getKuerzel() {
            return kuerzel;
        }

        Figur(String kuerzel) {
            this.kuerzel = kuerzel;
        }

        abstract double flaeche(double a, double b);
    }

    public void enumTest1(double a, double b){
        for(Figur figur : Figur.values()){
            System.out.println("Die Fläche von " +figur.name()+" ("+figur.getKuerzel().toString()+") ist: "+figur.flaeche(a,b));
        }
    }
}
