package klassen.klassenTest

import org.junit.Test

/**
 * Package: klassen.klassenTest
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 27.02.2018 2018
 */
class ComputerGroovyTest {
    void setUp() {
        super.setUp()
    }
    void tearDown() {
    }
@Test
    void testGetPrice() {
    }

    void testDatenBlatt() {
    }
}
