package klassen.klassenTest;

import org.junit.jupiter.api.Test;

import static junit.framework.TestCase.assertTrue;

/**
 * Package: klassen.klassenTest
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 01.02.2018 2018
 */
class ComputerTest {
@Test
    void testComp(){
        assertTrue(4==2*2);

    }

}