package klassen.klassenTest;

import klassen.tiere.Hund;
import klassen.tiere.Mensch;
import org.junit.jupiter.api.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Package: klassen.klassenTest
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 26.02.2018 2018
 */
class HundTest {

    static Hund hund = null;
    static Mensch herl = null;
    static int alter = 0;

    @BeforeAll
    static void setUp() {
        hund = new Hund();
        herl = new Mensch("Son", alter);
        hund.setHerrl(herl);
    }

    @DisplayName("HundTest get Tierart")
    @Test
    void getTierArt() {
        assertTrue("ein Hund".equalsIgnoreCase(hund.getTierArt()));
    }

    @DisplayName("cho can1!")
    @Test
    void bite() {
        assertFalse("Ang ang oi".equalsIgnoreCase(hund.bite()));
        assertEquals("Ang ang!", hund.bite());
        assertTrue(alter == 1);
    }
    @DisplayName("cho can2!")
    @Test
    void biteHurt() {
        assertEquals("Ang ang!", hund.bite());
        assertTrue(alter == 2);
    }

    @AfterEach
    void resetHund() {
        hund.herrl.setAlter(alter++);
    }

    @AfterAll
    static void clean() {
        hund = null;
    }

}