package klassen.klassenTest

import spock.lang.Specification

/**
 * Package: klassen.klassenTest
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 28.02.2018 2018
 */
class StringRegexSpockTest extends Specification {
    void setup() {
    }

    void cleanup() {
    }

    def "StringRegexSplit"() {
    }

    def "StringBlanc"() {
    }
}
