package klassen.klassenTest;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Package: klassen.klassenTest
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 27.02.2018 2018
 */
class StringRegexTest {

    @BeforeEach
    void setUp() {
    }

    @AfterEach
    void tearDown() {
    }

    @Test
    void stringRegexSplit() {
    }

    @Test
    void stringBlanc() {
    }
}