package klassen.klassenTest;

import klassen.SuperInitializer;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 05.02.2018 2018
 */
public class SubInitializer extends SuperInitializer {
    int i = 5;

    static {
        System.out.println("SubInitializer Static");
    }

    {
        System.out.println("SubInitializer instance initializer");
        foo();
        fixMethode();
    }

    public SubInitializer() {
        System.out.println("SubInitializer constructor");
    }

    public SubInitializer(int i) {
        System.out.println("SubInitializer constructor with para " + i);
    }

    public void foo() {
        System.out.println("SubMethode Foo! " + i);
    }

    public void fixMethode() {
        System.out.println("SubMethode FixMethode");
    }
}
