package klassen;

import org.omg.CORBA.TCKind;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 29.01.2018 2018
 */
public class Computer {
    String processor;
    String graficCard;
    int ram;
    int price;

    public Computer(String derProcesser, String dieGraficCard, int derRam, int derPrice) {
        this.processor = derProcesser;
        this.graficCard = dieGraficCard;
        this.ram = derRam;
        this.price = derPrice;

    }

    public int getPrice() {
        return price;
    }

    public String datenBlatt() {
        String daten = "Processor: " + processor + "\n Grafic: " + graficCard + "\n Ram: " + ram + "\n Price:" + price;
        return daten;

    }
}
