package klassen;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 31.01.2018 2018
 */
public class CustomerThread extends  Thread{
    String name;
    Integer counter;
    public CustomerThread(String _name, Integer _counter){
        this.name = _name;
        this.counter = _counter;
    }
    public void run() {
        System.out.println("Starte Thread: " + name);
        synchronized (counter) { // Threads darf nur nach einander auf counter zugreifen
            try {
                for(int i =0; i<3; i++){
                    System.out.println(counter++);
                }
                Thread.sleep(100);
            } catch (Exception e) {
                e.printStackTrace();
            }
            System.out.println("Beende Thread: " + name);
        }
    }
}
