package klassen;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 01.02.2018 2018
 */
public class CustomerThreadDeadlock extends CustomerThread {
    unDeadLock unDeadLock;
    boolean flag;

    public CustomerThreadDeadlock(String _name, Integer _counter, unDeadLock _deadLock, boolean _flag) {
        super(_name, _counter);
        this.unDeadLock = _deadLock;
        this.flag = _flag;
    }
    public void run(){
        System.out.println("Starte: "+ name);
        for(int i = 0; i<5; i++){
            if(!flag)
            unDeadLock.first();
            else
                unDeadLock.second();

        }
    }
}
