package klassen;

import java.util.ArrayList;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 30.01.2018 2018
 */
public class Generic {
    ArrayList<Notebook> noteList = new ArrayList<Notebook>();

    public Generic() {

    }

    public ArrayList<Notebook> generickList() {

        noteList.add(new Notebook("Intel", "MX", 4, 1300, 0, false));
        noteList.add(new Notebook("Intel1", "MX1", 4, 1301, 1, false));
        noteList.add(new Notebook("Intel2", "MX2", 4, 1302, 2, false));

        return noteList;
    }

    public void printList(ArrayList<Notebook> list) {
        System.out.println("Ausgabe aus: " + getClass().getName());
        for (Notebook note : list) {
            System.out.println(note.datenBlatt());
        }
    }
    private void print(){

    }
}
