package klassen;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 05.02.2018 2018
 */
public class Initializer {

    int check = 1;

    static { // immmer ausgeführt mit der Klasse
        System.out.println("Initialize: Static");
    }

    {  // instanzInitializer immer wenn instanziert
        System.out.println("Instance Initializer " + check);
        testMethode();
    }

    public Initializer() {
        System.out.println("Constructor Initializer " + check);
    }
    public void testMethode() {
        try {
            System.out.println(getClass().getMethod("testMethode").getName());
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        }
    }
}
