package klassen;

import java.util.ArrayList;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 06.02.2018 2018
 */
public class LaufZeit {
    public void konstanteLZ(ArrayList<String> s) {
        int x = 1 + 1;
        s.get(0);
    }

    public void lineareLZ(ArrayList<String> s) {
        for (int i = 0; i < s.size(); i++) {
            s.set(5, "Bla");
        }
    }


    public void quadratischeLZ(ArrayList<String> s) {
        for (int i = 0; i < s.size(); i++) {
            if (s.get(i).equals("")) {
                //do something
            }
        }
    }

    public void logarythmischeLZ(ArrayList<String> s) {

    }

    public int exponentielleLZ(int i) {
       return exponentielleLZ(i - 1) + exponentielleLZ(i - 2);
    }

}

