package klassen;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.*;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 15.02.2018 2018
 */
public class MainLogger {

    private Logger log = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);
    public MainLogger() {

    Logger root = Logger.getLogger(""); // root logger
    FileHandler txt = null;
        try {
            txt = new FileHandler("log.txt");
        } catch (IOException e) {
            e.printStackTrace();
        }

        root.setLevel(Level.ALL);
        txt.setFormatter(new Formatter() { // set format in
            @Override
            public String format(LogRecord record) {
                String ret ="";
                if(record.getLevel().intValue() >= Level.WARNING.intValue()) {
                    ret += "Attention: ";
                }
                ret += record.getLevel();
                SimpleDateFormat dateFormat = new SimpleDateFormat(" dd MM yyyy HH:mm:sss ");
                Date date = new Date(record.getMillis());
                ret += dateFormat.format(date);
                ret += this.formatMessage(record);
                ret += "\r\n";

                return ret;
            }
        });
        root.addHandler(txt);

    }
    public void logWriter(){
        log.severe("Error happened");
        log.warning("Warning log");
        log.info("log Info");
        log.fine("Alles Fine");
        log.config("Log Config");
    }
    public void logInfo(String message){
        log.info(message);
    }
    public void logFine(String message){
        log.fine(message);
    }

}