package klassen;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 29.01.2018 2018
 */
public class Notebook extends Computer {
    int weight;
    boolean convertible;
    public Notebook(String derProcesser, String dieGraficCard, int derRam, int derPrice, int dasGewicht, boolean dasConvertible) {
        super(derProcesser, dieGraficCard, derRam, derPrice);
        this.weight = dasGewicht;
        this.convertible = dasConvertible;
    }
    @Override
    public String datenBlatt(){
        String daten = "Processor: "+processor+"\n Grafic: " +graficCard+"\n Ram: "+ram +"\n Price:"+ price +"\n Weight: "+ weight;
        return daten;
    }
}
