package klassen;

import klassen.tiere.Hund;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 13.02.2018 2018
 */
public class Reflection {
    public void reflectionTier(){
        Hund hund = new Hund();
        Class myClass = Hund.class;
        Field field = null;
        Method privMeth = null;
        try {
            privMeth = myClass.getDeclaredMethod("neuHerrchen", int.class);
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        }
        try {
            field = myClass.getDeclaredField("herrchen");

        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        }
        field.setAccessible(true);
        privMeth.setAccessible(true);
        try {
            privMeth.invoke(hund,4);
            System.out.println(hund.getClass().getName()+" Field: "+field.getName()+" "+field.getType()+":"+field.getInt(hund));
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }
    }
}
