package klassen;

import java.util.TimerTask;
import java.util.Timer;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 11.02.2018 2018
 */
public class Time {
    public static int count = 0;

    public void timing() {
        Timer t = new Timer();

        t.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                if (count >=3) {
                    System.out.println("Timer will stopped:");
                    t.cancel();
                }
                System.out.println(getClass().getName()+" Run spcific task at given time.");
                count++;
            }
        }, 2 * 10000, 2 * 1000);

    }


}
