package klassen;

import java.util.Iterator;
import java.util.TreeSet;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 12.02.2018 2018
 */
public class TreeSets {
    public void treeSetAusgeben(){
        TreeSet<MyCompareable> treeSet = new TreeSet<MyCompareable>();
        treeSet.add(new MyCompareable(1,2));
        treeSet.add(new MyCompareable(3,4));
        treeSet.add(new MyCompareable(5,6));
        treeSet.add(new MyCompareable(9,10));
        treeSet.add(new MyCompareable(7,8));
        Iterator<MyCompareable> i = treeSet.iterator();
        while (i.hasNext()){
            System.out.println(i.next().b);
        }
    }

}
