package klassen;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 16.02.2018 2018
 */
public class WebCrawler {
    public void siteCrawler(String webLink) {
        BufferedReader bufferedReader = null;
        InputStreamReader inputStreamReader = null;
        URL url = null;

        String urlString = webLink;
        try {
            url = new URL(urlString);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        // open stream
        try {
            inputStreamReader = new InputStreamReader(url.openStream());
        } catch (IOException e) {
            e.printStackTrace();
        }
        bufferedReader = new BufferedReader(inputStreamReader);

        // inLine operation

        String line = null;
        ArrayList<String> allLinks = new ArrayList<String>();
        try {
            while ((line = bufferedReader.readLine()) != null) {
                if (line.contains("watch?v=")) {
                    String subString = line; // ein Substring wie die Zeile generiert
                    subString = subString.substring(subString.indexOf("watch?") - 1, subString.indexOf("watch?") + 19); // ein Substring generiert mit VideoLink
                    allLinks.add(webLink+subString);
                }
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
        for(String link : allLinks){
            System.out.println(link);
        }
    }
}
