package klassen.dateiHangling;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 31.01.2018 2018
 */
public class DateinSchreiben {
        String text = "";

        public String Schreiben(String url) throws IOException {
            FileWriter file = new FileWriter(url);
            Scanner sc = new Scanner(System.in);
            String eingabe = "";
            while (!eingabe.equals("q")) {
                eingabe = sc.nextLine();
                file.write(eingabe+"\n");
            }
            sc.close();
            file.close();
            return text;

        }
        public void printDatei(String text){
            System.out.println("Ausgabe aus: " + getClass().getName());
            System.out.println(text);
        }
    }



