package klassen.dateiHangling;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 30.01.2018 2018
 */
public class DateinLesen {
    String text = "";

    public String lesen(String url) throws FileNotFoundException {
        File datei = new File(url);
        Scanner sc = new Scanner(datei);
        while (sc.hasNextLine()) {
            text = text + sc.nextLine()+"\n";
        }
        sc.close();
        return text;

    }
    public void printDatei(String text){
        System.out.println("Ausgabe aus: " + getClass().getName());
        System.out.println(text);
    }
}
