package klassen.annotations;

/**
 * Package: klassen.annotations
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 19.02.2018 2018
 */
@FunctionalInterface
public interface AnnotationC {

     void shown();
}
