package klassen.annotations;

/**
 * Package: klassen.annotations
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 19.02.2018 2018
 */
public class Annotation {
    String name;

    public void show() {
        System.out.println(" Annotation in Anotation");
    }
}

