package klassen.annotations;

/**
 * Package: klassen.annotations
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 19.02.2018 2018
 */
public class AnnotationB extends AnnotationA {


    protected void checkAnnotation(){
        AnnotationA annotationA = new AnnotationA();
                annotationA.shown();
                annotationA.show();
    }
}
