package klassen.annotations;

/**
 * Package: klassen.annotations
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 19.02.2018 2018
 */
@SmartFone(os = "Android", version = 6)
public class Nokia {
}
