package klassen.annotations;

import java.lang.annotation.*;

/**
 * Package: klassen.annotations
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 19.02.2018 2018
 */
@Documented
@Inherited
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface SmartFone {
    String os() default "Symbian";
    int version() default 1;
}
