package klassen.server;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;

/**
 * Package: klassen.server
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 18.02.2018 2018
 */
public class Client {
    public static void main(String[] arg){
        try {
            Socket client = new Socket("localhost",9090);
            DataOutputStream output = new DataOutputStream(client.getOutputStream());
            output.writeUTF("hi am Son at: "+client.getRemoteSocketAddress());

            DataInputStream input = new DataInputStream(client.getInputStream());
            System.out.println("Client read Input: "+input.readUTF());
            client.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
