package klassen.Liste;

/**
 * Package: klassen.Liste
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 05.03.2018 2018
 */
public class Element {
    public String current;
    public Element next = null;

    public Element(String s){
        this.current = s;
    }

}
