package klassen.Liste;

/**
 * Package: klassen.Liste
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 05.03.2018 2018
 */
public class ListOperator {
    Element first = null;

    public Element pop() {
        if (first == null) {
            return null;
        } else {
            Element popEle = first;
            this.first = first.next;
            return popEle;
        }
    }

    public void push(Element element) {
        if (this.first == null) {
            first = element;
        } else {
            Element iterator = first;
            while (iterator.next != null) {
                iterator = iterator.next;
            }
            iterator.next = element;
        }
    }

    public Element stackOff() {
        if (first == null) {
            return first;
        }else{
            Element off = first;
            first = first.next;
            return off;
        }
    }
}
