package klassen.tiere;

import java.util.ArrayList;

/**
 * Package: klassen.tiere
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 07.02.2018 2018
 */
public class GenericTier< T extends Tier, E extends Hund> {
    private T value;
    private E last;
    private T next;


    public T selectT(){
        value.setBeine(3);
        return value;
    }

    protected  ArrayList<? extends Hund> massenKastration(ArrayList<? extends Hund> list){
        for(Hund i: list){
            i.setKasttrtion(true);
        }
        return list;
    }
    public void printTierList(ArrayList<?> list){
       for(Object i: list){

           if(i instanceof Hund){
               System.out.println("Bin ein Hund aus der Liste "+ ((Hund) i).tierArt);
           }System.out.println("Bin ein Element aus der Liste "+  i.getClass().getName());

       }
    }
    public void makeList(ArrayList<? extends Hund> tierchen){
        for(Object i: tierchen) {

            if (i instanceof Hund) {
                System.out.println("Bin ein Hund aus der Liste " + ((Hund) i).tierArt);
            }
            System.out.println("Bin ein Element aus der Liste Tierchen " + i.getClass().getName());



    }
    }
}
