package klassen.tiere;

/**
 * Package: klassen.tiere
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 02.02.2018 2018
 */
public class Hund extends Tier{


    private transient int herrchen = 2;
    private void neuHerrchen(int x){
        herrchen = x;

    }

    public void setHerrchen(int herrchen) {
        this.herrchen = herrchen;
    }

    public Hund(){
        this.beine = 4;
        this.tierArt = "ein Hund";
    }

    @Override
    public String getTierArt() {
        return tierArt;
    }

    @Override
    public void voice(){
        System.out.println("Wuw, wuw!");
    }

    @Override
    public void doSomething(int i){
        System.out.println("Oang, Oang!");
        if(i==0){
            return;
        }
        else super.doSomething(i);
    }
    public String bite(){
        return "Ang ang!";
    }
}
