package klassen.tiere;

/**
 * Package: klassen.tiere
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 02.02.2018 2018
 */
public class Katze extends Tier {


    public Katze() {
        this.beine = 4;
        this.tierArt = "eine Katze";
    }

    @Override
    public void voice() {
        System.out.println("Miao, Miao!, Beine:" + beine);
    }

    @Override
    public String getTierArt() {
        return tierArt;
    }

    @Override
    public Katze clone() {
        Katze katz = (Katze) super.clone();
        Mensch mensch = this.herrl.clone();
        katz.setHerrl(mensch);

        return katz;
    }


}
