package klassen.tiere;

/**
 * Package: klassen.tiere
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 22.02.2018 2018
 */
public class Mensch implements Cloneable{
    String name;
    int alter;

    public void setName(String name) {
        this.name = name;
    }

    public void setAlter(int alter) {
        this.alter = alter;
    }

    public String getName() {
        return name;
    }

    public Mensch(String name, int alter){
        this.alter = alter;
        this.name = name;
    }
    @Override
    public Mensch clone(){
        try {
            return (Mensch) super.clone();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
        }
        return null;
    }
}
