package swing;

import javax.swing.*;

/**
 * Package: swiing
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 07.02.2018 2018
 */
public class FirstForm {
    private JButton button1;
    private JList list1;
}
