package klassen.Json;

import com.google.gson.*;
import klassen.tiere.Hund;

import java.io.*;

/**
 * Package: klassen.Json
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 15.03.2018 2018
 */
public class Json {
    public Json() {
    }

    public JsonObject JsonReadFile(String url) throws Exception {
        Object obj = new JsonParser().parse(new FileReader(url));
        JsonObject jsonObject = (JsonObject) obj;
        return jsonObject;

    }

    public JsonObject JsonAdd(JsonObject jObject, String label, Object obj) {
        jObject.addProperty("Son", obj.toString());
        return jObject;
    }

    public void printJson(JsonObject jsonObject) {
        jsonObject.addProperty("Son", 12);
        jsonObject.get("glosary");
        System.out.println(jsonObject + "  " + jsonObject.get("Son"));
    }

    public String objectToJson(Object obj, String url) {
        GsonBuilder builder = new GsonBuilder();
        Gson gson = builder.create();
        FileWriter writer = null;
        try {
            writer = new FileWriter(url);
            writer.write(gson.toJson(obj));
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        // 2. Java object to JSON, and assign to a String
        return gson.toJson(obj);
    }

    public Hund jsonToObject(String url) throws FileNotFoundException {
        GsonBuilder builder = new GsonBuilder();
        Gson gson = builder.create();
        BufferedReader bufferedReader = new BufferedReader(
                new FileReader(url));

        Hund obj = (Hund)gson.fromJson(bufferedReader, Hund.class);
       return obj;
    }

}
