package klassen.java8;

import klassen.MainLogger;

/**
 * Package: klassen.Lamda
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 18.02.2018 2018
 */
public class Lamda {
    MainLogger log = new MainLogger();

    public void lamdaAusdruck(int x, int y){
        Mathe addieren = (int a, int b) -> a+b;
        Mathe multiplizieren = (a, b) -> { return a*b;};
        log.logInfo(getClass().getName()+" addierenNeu: "+ addieren.funkt(x,y));
        //System.out.println(getClass().getName()+" addieren: "+ addieren.funkt(x,y));
        System.out.println(getClass().getName()+"multiplizieren: "+ multiplizieren.funkt(x,y));

    }
    interface Mathe{
        int funkt(int a, int b);
    }

}
