package klassen.java8;

import java.time.*;
import java.time.format.DateTimeFormatter;

/**
 * Package: klassen
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 12.02.2018 2018
 */
public class Time8 {
    public void timing8(){
        Clock clock = Clock.systemUTC();
        Instant start = clock.instant();
        System.out.println("Timer in Java8, UTC Instant Start: "+start);
        Instant end = clock.instant();
        Instant ende = Instant.now();
        System.out.println("Timer in Java8, UTC Instant end: "+end);
        System.out.println("Timer in Java8, UTC Instant ende: "+ende);
        Duration duration = Duration.between(start, end);
        System.out.println("Timer in Java8, UTC Duration start-ende: "+duration);
        LocalTime localTime = LocalTime.now();
        System.out.println("Local time of clock now: "+localTime);
        LocalDateTime localDateTime = LocalDateTime.now();
        System.out.println("LocalDateTime time of now: "+localDateTime);
        LocalDateTime dt = LocalDateTime.of(2018,2,12,12,00,0,01);

        String pattern = "MM-dd-yyyy HH:mm:ss"; //Case Sensitive
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern(pattern);
        System.out.println("SystemDateTime nach Format: "+dtf.format(localDateTime));



    }
}
